//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LULU_Model_DLL
{
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.AtttendedClasses = new HashSet<AtttendedClass>();
        }
        [DataMember]
        public int ClassID { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public System.DateTime ClassDate { get; set; }
        [DataMember]
        public bool Compulsory { get; set; }
        [DataMember]
        public System.TimeSpan StartTime { get; set; }
        [DataMember]
        public System.TimeSpan EndTime { get; set; }

        [IgnoreDataMember]
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [IgnoreDataMember]
        public virtual ICollection<AtttendedClass> AtttendedClasses { get; set; }
        [IgnoreDataMember]
        public virtual ClassRoom ClassRoom { get; set; }
    }
}
